<?php
/**
 * Created by PhpStorm.
 * User: vinhnguyenducthuy
 * Date: 11/16/16
 * Time: 8:23 AM
 */

namespace Magestore\Student\Model\ResourceModel\ManagerStudent;
use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{
    protected $_idFieldName = 'student_id';
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('Magestore\Student\Model\ManagerStudent','Magestore\Student\Model\ResourceModel\ManagerStudent');
    }
}